id = "basedpyright"
name = "BasedPyright"
description = "Python type checking and language server support from BasedPyright."
version = "0.1.3"
schema_version = 1
authors = ["Jose Miguel <miguelpintojose00@gmail.com>"]
repository = "https://github.com/pub-struct/basedpyright-zed"

[language_servers.basedpyright]
name = "BasedPyright"
languages = ["Python"]
