id = "basedpyright-alt"
name = "BasedPyright Alt"
description = "Python type checking and language server support from BasedPyright."
version = "0.1.3"
schema_version = 1
authors = ["Justin Pallansch <pallanschja@gmail.com>"]
repository = "https://github.com/jpal91/basedpyright-zed"

[language_servers.basedpyright-alt]
name = "BasedPyright Alt"
languages = ["Python"]
